"use client";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Canvas from "./Canvas";
import "./globals.css";
import ClearButton from "./ClearButton";
import GuessButton from "./GuessButton";

const inter = Inter({subsets: ["latin"]});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Canvas width={600} height={600}/>
        <ClearButton/>
        <GuessButton/>
        </body>
        </html>
    );
}
